trigger:
  branches:
    include:
      - testen
  # tags:
  #   include:
  #     - release-v*

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/pipeline-fe

parameters:
  - name: btdBuild
    type: boolean
    default: true
  - name: btdTest
    type: boolean
    default: true
  - name: btdDeploy
    type: boolean
    default: true

jobs:
  - template: pipelines/jobs/apps/btd-koppel-api.yaml@MamsInfra
    parameters:
      appServiceShortName: wmo
      dtapName: ${{ variables.dtapName }}
      btdBuild: ${{ parameters.btdBuild }}
      btdTest: ${{ parameters.btdTest }}
      btdDeploy: ${{ parameters.btdDeploy }}
